In [1]:
import zipfile
import os

zip_path = "data/cart_dataset.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    print("Files inside ZIP:\n")
    
    for info in z.infolist():
        print(
            info.filename,
            "| Compressed:",
            round(info.compress_size / (1024**2), 2), "MB",
            "| Uncompressed:",
            round(info.file_size / (1024**2), 2), "MB"
        )

Files inside ZIP:

2019-Nov.csv | Compressed: 2740.98 MB | Uncompressed: 8589.52 MB
2019-Oct.csv | Compressed: 1652.33 MB | Uncompressed: 5406.01 MB

In [4]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\tejas k m\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\tejas k m\AppData\Roaming\Python\Python311\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\tejas k m\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 2.8 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.9 MB 4.2 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.9 MB 4.3 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.9 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 3.8 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.3 MB/s  0:00:03
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\tejas k m\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import zipfile

zip_path = "data/cart_dataset.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    
    # Change this if your filename is different
    with z.open("2019-Oct.csv") as f:
        
        df_sample = pd.read_csv(
            f,
            nrows=10000
        )

print("Rows:", df_sample.shape[0])
print("Columns:", df_sample.shape[1])

df_sample.head()

Rows: 10000
Columns: 9

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [3]:
df_sample.columns.tolist()

['event_time',
 'event_type',
 'product_id',
 'category_id',
 'category_code',
 'brand',
 'price',
 'user_id',
 'user_session']

In [4]:
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     10000 non-null  str
 1   event_type     10000 non-null  str
 2   product_id     10000 non-null  int64
 3   category_id    10000 non-null  int64
 4   category_code  6723 non-null   str
 5   brand          8558 non-null   str
 6   price          10000 non-null  float64
 7   user_id        10000 non-null  int64
 8   user_session   10000 non-null  str
dtypes: float64(1), int64(3), str(5)
memory usage: 703.3 KB

In [5]:
df_sample.isnull().sum()

event_time          0
event_type          0
product_id          0
category_id         0
category_code    3277
brand            1442
price               0
user_id             0
user_session        0
dtype: int64

In [6]:
df_sample["event_type"].value_counts()

event_type
view        9785
purchase     118
cart          97
Name: count, dtype: int64

In [7]:
files = ["2019-Oct.csv", "2019-Nov.csv"]

for filename in files:
    
    print("\n" + "="*60)
    print(filename)
    print("="*60)
    
    with zipfile.ZipFile(zip_path, "r") as z:
        
        with z.open(filename) as f:
            
            sample = pd.read_csv(f, nrows=10000)
            
            print("Shape:", sample.shape)
            print("Columns:")
            print(sample.columns.tolist())
            
            if "event_type" in sample.columns:
                print("\nEvent types:")
                print(sample["event_type"].value_counts())

============================================================
2019-Oct.csv
============================================================
Shape: (10000, 9)
Columns:
['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

Event types:
event_type
view        9785
purchase     118
cart          97
Name: count, dtype: int64

============================================================
2019-Nov.csv
============================================================
Shape: (10000, 9)
Columns:
['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']

Event types:
event_type
view        9805
purchase     102
cart          93
Name: count, dtype: int64

In [8]:
chunksize = 100000

with zipfile.ZipFile(zip_path, "r") as z:
    
    with z.open("2019-Oct.csv") as f:
        
        for chunk in pd.read_csv(
            f,
            chunksize=chunksize
        ):
            
            chunk = chunk[
                chunk["event_type"].isin(
                    ["view", "cart", "purchase"]
                )
            ]
            
            # Continue analysis...

In [9]:
import zipfile

zip_path = "data/cart_dataset.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    print(z.namelist())

['2019-Nov.csv', '2019-Oct.csv']

In [10]:
with zipfile.ZipFile(zip_path, "r") as z:
    
    with z.open("2019-Oct.csv") as f:
        df_sample = pd.read_csv(f, nrows=10000)

print(df_sample.columns.tolist())
print(df_sample["event_type"].value_counts())

['event_time', 'event_type', 'product_id', 'category_id', 'category_code', 'brand', 'price', 'user_id', 'user_session']
event_type
view        9785
purchase     118
cart          97
Name: count, dtype: int64

In [11]:
import shutil

total, used, free = shutil.disk_usage(".")

print("Free space:", round(free / (1024**3), 2), "GB")

Free space: 79.73 GB

In [12]:
import psutil

ram = psutil.virtual_memory()

print("Total RAM:", round(ram.total / (1024**3), 2), "GB")
print("Available RAM:", round(ram.available / (1024**3), 2), "GB")

Total RAM: 15.65 GB
Available RAM: 3.17 GB

In [28]:
import pandas as pd
import zipfile

zip_path = "data/cart_dataset.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("2019-Oct.csv") as f:
        df = pd.read_csv(f, nrows=200000)

print("Dataset shape:", df.shape)

Dataset shape: (200000, 9)

In [29]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [30]:
df["event_type"].value_counts()

event_type
view        193377
purchase      3639
cart          2984
Name: count, dtype: int64

In [31]:
print(
    "Memory used:",
    round(df.memory_usage(deep=True).sum() / (1024**2), 2),
    "MB"
)

Memory used: 74.19 MB

In [32]:
df.to_csv(
    "ecommerce_100k_sample.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [33]:
print(df.shape)

(200000, 9)

In [34]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     200000 non-null  str
 1   event_type     200000 non-null  str
 2   product_id     200000 non-null  int64
 3   category_id    200000 non-null  int64
 4   category_code  135756 non-null  str
 5   brand          171489 non-null  str
 6   price          200000 non-null  float64
 7   user_id        200000 non-null  int64
 8   user_session   200000 non-null  str
dtypes: float64(1), int64(3), str(5)
memory usage: 13.7 MB

In [36]:
missing = df.isnull().sum()

print(missing)

event_time           0
event_type           0
product_id           0
category_id          0
category_code    64244
brand            28511
price                0
user_id              0
user_session         0
dtype: int64

In [37]:
missing_percentage = (
    df.isnull().sum() / len(df) * 100
).round(2)

print(missing_percentage)

event_time        0.00
event_type        0.00
product_id        0.00
category_id       0.00
category_code    32.12
brand            14.26
price             0.00
user_id           0.00
user_session      0.00
dtype: float64

In [38]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 138

In [39]:
# Check size before deletion
print("Before:", df.shape)

# Remove rows with missing brand or category_code
df = df.dropna(subset=['brand', 'category_code'])

print("After:", df.shape)

Before: (200000, 9)
After: (124891, 9)

In [40]:
print(df.isnull().sum())

event_time       0
event_type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
user_session     0
dtype: int64

In [41]:
removed = 200000 - len(df)

print("Rows removed:", removed)
print("Rows remaining:", len(df))
print("Percentage remaining:", round(len(df) / 200000 * 100, 2), "%")

Rows removed: 75109
Rows remaining: 124891
Percentage remaining: 62.45 %

In [42]:
print("Before removing duplicates:", df.shape)

df = df.drop_duplicates().reset_index(drop=True)

print("After removing duplicates:", df.shape)

Before removing duplicates: (124891, 9)
After removing duplicates: (124817, 9)

In [43]:
print("Duplicates remaining:", df.duplicated().sum())

Duplicates remaining: 0

In [44]:
print(df['event_type'].value_counts())

event_type
view        119589
purchase      2704
cart          2524
Name: count, dtype: int64

In [45]:
print("Current rows:", len(df))
print("Current columns:", len(df.columns))

Current rows: 124817
Current columns: 9

In [46]:
print(df['event_type'].value_counts().sum())

124817

In [47]:
session_analysis = df.groupby('user_session').agg(
    user_id=('user_id', 'first'),
    views=('event_type', lambda x: (x == 'view').sum()),
    cart_events=('event_type', lambda x: (x == 'cart').sum()),
    purchase_events=('event_type', lambda x: (x == 'purchase').sum()),
    session_start=('event_time', 'min'),
    session_end=('event_time', 'max')
).reset_index()

In [48]:
session_analysis.head()

,user_session,user_id,views,cart_events,purchase_events,session_start,session_end
0,0005957a-094f-4c99-afd1-448bd7d8139a,513391929,1,0,0,2019-10-01 04:44:08 UTC,2019-10-01 04:44:08 UTC
1,0006852b-f9a2-4d84-b439-acc1f9e6771e,536297355,1,0,0,2019-10-01 03:21:44 UTC,2019-10-01 03:21:44 UTC
2,000c2fd2-561a-4abd-bd21-5e71449b1b78,552296408,2,0,0,2019-10-01 03:58:25 UTC,2019-10-01 03:58:47 UTC
3,000c8aaa-d614-433a-9621-a53629f39fd9,555477511,1,0,0,2019-10-01 03:59:05 UTC,2019-10-01 03:59:05 UTC
4,00104b92-2cd3-440c-9995-e2c86bee04ea,554050381,1,0,0,2019-10-01 05:41:29 UTC,2019-10-01 05:41:29 UTC

In [49]:
def classify_session(row):
    if row['purchase_events'] > 0:
        return 'Purchased'
    elif row['cart_events'] > 0:
        return 'Abandoned Cart'
    else:
        return 'Browsed Only'

session_analysis['session_status'] = session_analysis.apply(
    classify_session,
    axis=1
)

In [50]:
session_analysis['session_status'].value_counts()

session_status
Browsed Only      29665
Purchased          2332
Abandoned Cart      660
Name: count, dtype: int64

In [51]:
# Sessions that added something to cart
cart_sessions = session_analysis[
    session_analysis['cart_events'] > 0
]

# Cart sessions that eventually purchased
converted_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] > 0
]

# Cart sessions with no purchase
abandoned_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] == 0
]

print("Total Cart Sessions:", len(cart_sessions))
print("Converted Cart Sessions:", len(converted_cart_sessions))
print("Abandoned Cart Sessions:", len(abandoned_cart_sessions))

Total Cart Sessions: 1608
Converted Cart Sessions: 948
Abandoned Cart Sessions: 660

In [52]:
cart_abandonment_rate = (
    len(abandoned_cart_sessions) /
    len(cart_sessions)
) * 100

cart_conversion_rate = (
    len(converted_cart_sessions) /
    len(cart_sessions)
) * 100

print("Cart Abandonment Rate:", round(cart_abandonment_rate, 2), "%")
print("Cart Conversion Rate:", round(cart_conversion_rate, 2), "%")

Cart Abandonment Rate: 41.04 %
Cart Conversion Rate: 58.96 %

In [53]:
category_analysis = cart_sessions.groupby('category_code').agg(
    cart_sessions=('user_session', 'count'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

category_analysis['abandoned_sessions'] = (
    category_analysis['cart_sessions']
    - category_analysis['converted_sessions']
)

category_analysis['abandonment_rate'] = (
    category_analysis['abandoned_sessions']
    / category_analysis['cart_sessions']
) * 100

category_analysis = category_analysis.sort_values(
    'abandonment_rate',
    ascending=False
)

category_analysis.head(10)

KeyError: 'category_code'

In [54]:
cart_events = df[df['event_type'] == 'cart'].copy()

cart_category = cart_events[
    ['user_session', 'category_code']
].drop_duplicates()

cart_category.head()

                              user_session                category_code
343   0b74a829-f9d7-4654-b5b0-35bc9822c238       electronics.smartphone
398   e5ac3caa-e6d5-4d6b-ae06-2c18cd9ca683  electronics.audio.headphone
810   685b5b42-f597-4a69-ab4c-ef96a30bc454       electronics.smartphone
1029  f2cc68f7-39d1-4a50-9dcf-f2a0921bdfda       electronics.smartphone
1047  ce885079-4d92-4fe6-92a3-377c5a2d8291       electronics.smartphone

In [55]:
cart_category_analysis = cart_category.merge(
    cart_sessions[
        ['user_session', 'purchase_events']
    ],
    on='user_session',
    how='left'
)

cart_category_analysis.head()

,user_session,category_code,purchase_events
0,0b74a829-f9d7-4654-b5b0-35bc9822c238,electronics.smartphone,1
1,e5ac3caa-e6d5-4d6b-ae06-2c18cd9ca683,electronics.audio.headphone,1
2,685b5b42-f597-4a69-ab4c-ef96a30bc454,electronics.smartphone,0
3,f2cc68f7-39d1-4a50-9dcf-f2a0921bdfda,electronics.smartphone,2
4,ce885079-4d92-4fe6-92a3-377c5a2d8291,electronics.smartphone,3

In [56]:
category_analysis = cart_category_analysis.groupby(
    'category_code'
).agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

category_analysis['abandoned_sessions'] = (
    category_analysis['cart_sessions']
    - category_analysis['converted_sessions']
)

category_analysis['abandonment_rate'] = (
    category_analysis['abandoned_sessions']
    / category_analysis['cart_sessions']
) * 100

category_analysis = category_analysis.sort_values(
    'abandonment_rate',
    ascending=False
)

category_analysis.head(10)

,category_code,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,appliances.environment.air_heater,3,0,3,100.0
3,appliances.iron,1,0,1,100.0
31,kids.carriage,1,0,1,100.0
6,appliances.kitchen.microwave,1,0,1,100.0
8,appliances.kitchen.refrigerators,1,0,1,100.0
10,appliances.personal.scales,1,0,1,100.0
15,computers.ebooks,1,0,1,100.0
17,computers.peripherals.keyboard,1,0,1,100.0
32,kids.skates,1,0,1,100.0
18,computers.peripherals.mouse,1,0,1,100.0

In [57]:
category_analysis_filtered = category_analysis[
    category_analysis['cart_sessions'] >= 20
].sort_values(
    'abandonment_rate',
    ascending=False
)

category_analysis_filtered.head(10)

,category_code,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
29,electronics.video.tv,48,18,30,62.500000
24,electronics.audio.headphone,118,56,62,52.542373
25,electronics.clocks,45,26,19,42.222222
26,electronics.smartphone,1260,781,479,38.015873
1,appliances.environment.vacuum,25,16,9,36.000000

In [58]:
category_analysis_filtered.sort_values(
    'abandoned_sessions',
    ascending=False
).head(10)

,category_code,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
26,electronics.smartphone,1260,781,479,38.015873
24,electronics.audio.headphone,118,56,62,52.542373
29,electronics.video.tv,48,18,30,62.500000
25,electronics.clocks,45,26,19,42.222222
1,appliances.environment.vacuum,25,16,9,36.000000

In [59]:
cart_brand = df[df['event_type'] == 'cart'][
    ['user_session', 'brand']
].drop_duplicates()

cart_brand.head()

                              user_session    brand
343   0b74a829-f9d7-4654-b5b0-35bc9822c238    apple
398   e5ac3caa-e6d5-4d6b-ae06-2c18cd9ca683    apple
810   685b5b42-f597-4a69-ab4c-ef96a30bc454  samsung
1029  f2cc68f7-39d1-4a50-9dcf-f2a0921bdfda   huawei
1047  ce885079-4d92-4fe6-92a3-377c5a2d8291  samsung

In [60]:
cart_brand_analysis = cart_brand.merge(
    cart_sessions[
        ['user_session', 'purchase_events']
    ],
    on='user_session',
    how='left'
)

cart_brand_analysis.head()

                           user_session    brand  purchase_events
0  0b74a829-f9d7-4654-b5b0-35bc9822c238    apple                1
1  e5ac3caa-e6d5-4d6b-ae06-2c18cd9ca683    apple                1
2  685b5b42-f597-4a69-ab4c-ef96a30bc454  samsung                0
3  f2cc68f7-39d1-4a50-9dcf-f2a0921bdfda   huawei                2
4  ce885079-4d92-4fe6-92a3-377c5a2d8291  samsung                3

In [61]:
brand_analysis = cart_brand_analysis.groupby(
    'brand'
).agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

brand_analysis['abandoned_sessions'] = (
    brand_analysis['cart_sessions']
    - brand_analysis['converted_sessions']
)

brand_analysis['abandonment_rate'] = (
    brand_analysis['abandoned_sessions']
    / brand_analysis['cart_sessions']
) * 100

In [62]:
brand_analysis_filtered = brand_analysis[
    brand_analysis['cart_sessions'] >= 20
]

In [63]:
brand_analysis_filtered.sort_values(
    'abandonment_rate',
    ascending=False
).head(10)

,brand,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
50,xiaomi,204,96,108,52.941176
13,huawei,102,61,41,40.196078
2,apple,480,291,189,39.375000
38,samsung,685,430,255,37.226277
31,oppo,42,29,13,30.952381

In [64]:
brand_analysis_filtered.sort_values(
    'abandoned_sessions',
    ascending=False
).head(10)

,brand,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
38,samsung,685,430,255,37.226277
2,apple,480,291,189,39.375000
50,xiaomi,204,96,108,52.941176
13,huawei,102,61,41,40.196078
31,oppo,42,29,13,30.952381

In [65]:
cart_product = df[df['event_type'] == 'cart'][
    ['user_session', 'product_id', 'category_code', 'brand', 'price']
].drop_duplicates()

cart_product.head()

,user_session,product_id,category_code,brand,price
343,0b74a829-f9d7-4654-b5b0-35bc9822c238,1002524,electronics.smartphone,apple,515.67
398,e5ac3caa-e6d5-4d6b-ae06-2c18cd9ca683,4804056,electronics.audio.headphone,apple,161.98
810,685b5b42-f597-4a69-ab4c-ef96a30bc454,1004833,electronics.smartphone,samsung,174.76
1029,f2cc68f7-39d1-4a50-9dcf-f2a0921bdfda,1005003,electronics.smartphone,huawei,258.21
1047,ce885079-4d92-4fe6-92a3-377c5a2d8291,1004750,electronics.smartphone,samsung,197.43

In [66]:
cart_product_analysis = cart_product.merge(
    cart_sessions[
        ['user_session', 'purchase_events']
    ],
    on='user_session',
    how='left'
)

cart_product_analysis.head()

,user_session,product_id,category_code,brand,price,purchase_events
0,0b74a829-f9d7-4654-b5b0-35bc9822c238,1002524,electronics.smartphone,apple,515.67,1
1,e5ac3caa-e6d5-4d6b-ae06-2c18cd9ca683,4804056,electronics.audio.headphone,apple,161.98,1
2,685b5b42-f597-4a69-ab4c-ef96a30bc454,1004833,electronics.smartphone,samsung,174.76,0
3,f2cc68f7-39d1-4a50-9dcf-f2a0921bdfda,1005003,electronics.smartphone,huawei,258.21,2
4,ce885079-4d92-4fe6-92a3-377c5a2d8291,1004750,electronics.smartphone,samsung,197.43,3

In [67]:
product_analysis = cart_product_analysis.groupby(
    ['product_id', 'category_code', 'brand']
).agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum()),
    average_price=('price', 'mean')
).reset_index()

product_analysis['abandoned_sessions'] = (
    product_analysis['cart_sessions']
    - product_analysis['converted_sessions']
)

product_analysis['abandonment_rate'] = (
    product_analysis['abandoned_sessions']
    / product_analysis['cart_sessions']
) * 100

In [68]:
product_analysis_filtered = product_analysis[
    product_analysis['cart_sessions'] >= 5
]

In [69]:
product_analysis_filtered.sort_values(
    'abandonment_rate',
    ascending=False
).head(10)

,product_id,category_code,brand,cart_sessions,converted_sessions,average_price,abandoned_sessions,abandonment_rate
261,4803977,electronics.audio.headphone,samsung,12,2,107.800000,10,83.333333
288,6000094,auto.accessories.alarm,starline,6,1,121.240000,5,83.333333
77,1004788,electronics.smartphone,xiaomi,5,1,133.672000,4,80.000000
196,1801690,electronics.video.tv,samsung,7,2,368.040000,5,71.428571
123,1005008,electronics.smartphone,xiaomi,13,4,103.080000,9,69.230769
61,1004739,electronics.smartphone,xiaomi,22,7,197.524091,15,68.181818
199,1801739,electronics.video.tv,samsung,6,2,282.200000,4,66.666667
108,1004903,electronics.smartphone,huawei,6,2,111.800000,4,66.666667
262,4804055,electronics.audio.headphone,apple,23,8,188.781304,15,65.217391
34,1004246,electronics.smartphone,apple,8,3,735.302500,5,62.500000

In [70]:
product_analysis_filtered.sort_values(
    'abandoned_sessions',
    ascending=False
).head(10)

,product_id,category_code,brand,cart_sessions,converted_sessions,average_price,abandoned_sessions,abandonment_rate
92,1004856,electronics.smartphone,samsung,140,94,130.760000,46,32.857143
97,1004870,electronics.smartphone,samsung,68,40,286.860000,28,41.176471
69,1004767,electronics.smartphone,samsung,101,75,254.764118,26,25.742574
62,1004741,electronics.smartphone,xiaomi,37,17,185.710000,20,54.054054
84,1004833,electronics.smartphone,samsung,52,34,174.752115,18,34.615385
0,1002524,electronics.smartphone,apple,35,18,514.864000,17,48.571429
264,4804295,electronics.audio.headphone,xiaomi,28,11,22.469286,17,60.714286
263,4804056,electronics.audio.headphone,apple,43,27,161.933488,16,37.209302
87,1004836,electronics.smartphone,samsung,29,13,241.181034,16,55.172414
262,4804055,electronics.audio.headphone,apple,23,8,188.781304,15,65.217391

In [71]:
price_analysis = cart_product_analysis.copy()

price_analysis['price_range'] = pd.cut(
    price_analysis['price'],
    bins=[0, 50, 100, 250, 500, 1000, float('inf')],
    labels=[
        '0-50',
        '51-100',
        '101-250',
        '251-500',
        '501-1000',
        '1000+'
    ]
)

In [72]:
price_summary = price_analysis.groupby(
    'price_range',
    observed=True
).agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

price_summary['abandoned_sessions'] = (
    price_summary['cart_sessions']
    - price_summary['converted_sessions']
)

price_summary['abandonment_rate'] = (
    price_summary['abandoned_sessions']
    / price_summary['cart_sessions']
) * 100

price_summary

,price_range,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,0-50,58,29,29,50.000000
1,51-100,68,43,25,36.764706
2,101-250,689,422,267,38.751814
3,251-500,428,288,140,32.710280
4,501-1000,269,174,95,35.315985
5,1000+,132,83,49,37.121212

In [73]:
price_summary = price_analysis.groupby(
    'price_range',
    observed=True
).agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum()),
    average_price=('price', 'mean')
).reset_index()

price_summary['abandoned_sessions'] = (
    price_summary['cart_sessions']
    - price_summary['converted_sessions']
)

price_summary['abandonment_rate'] = (
    price_summary['abandoned_sessions']
    / price_summary['cart_sessions']
) * 100

price_summary

,price_range,cart_sessions,converted_sessions,average_price,abandoned_sessions,abandonment_rate
0,0-50,58,29,27.250667,29,50.000000
1,51-100,68,43,84.158696,25,36.764706
2,101-250,689,422,158.752624,267,38.751814
3,251-500,428,288,324.359357,140,32.710280
4,501-1000,269,174,758.748972,95,35.315985
5,1000+,132,83,1355.538058,49,37.121212

In [74]:
df['event_time'] = pd.to_datetime(df['event_time'])

In [75]:
df['hour'] = df['event_time'].dt.hour
df['day_of_week'] = df['event_time'].dt.day_name()
df['date'] = df['event_time'].dt.date

In [76]:
cart_time = df[df['event_type'] == 'cart'][
    ['user_session', 'event_time']
].copy()

cart_time = cart_time.groupby('user_session').agg(
    cart_time=('event_time', 'min')
).reset_index()

In [77]:
cart_time_analysis = cart_time.merge(
    cart_sessions[
        ['user_session', 'purchase_events']
    ],
    on='user_session',
    how='left'
)

In [78]:
cart_time_analysis['hour'] = (
    cart_time_analysis['cart_time'].dt.hour
)

In [79]:
hour_analysis = cart_time_analysis.groupby('hour').agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

hour_analysis['abandoned_sessions'] = (
    hour_analysis['cart_sessions']
    - hour_analysis['converted_sessions']
)

hour_analysis['abandonment_rate'] = (
    hour_analysis['abandoned_sessions']
    / hour_analysis['cart_sessions']
) * 100

hour_analysis

,hour,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,0,2,2,0,0.000000
1,2,151,92,59,39.072848
2,3,359,215,144,40.111421
3,4,473,273,200,42.283298
4,5,559,328,231,41.323792
5,6,64,38,26,40.625000

In [80]:
cart_time_analysis['day_of_week'] = (
    cart_time_analysis['cart_time'].dt.day_name()
)

In [81]:
day_analysis = cart_time_analysis.groupby(
    'day_of_week'
).agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

day_analysis['abandoned_sessions'] = (
    day_analysis['cart_sessions']
    - day_analysis['converted_sessions']
)

day_analysis['abandonment_rate'] = (
    day_analysis['abandoned_sessions']
    / day_analysis['cart_sessions']
) * 100

day_analysis

,day_of_week,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,Tuesday,1608,948,660,41.044776

In [82]:
day_order = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
]

day_analysis['day_of_week'] = pd.Categorical(
    day_analysis['day_of_week'],
    categories=day_order,
    ordered=True
)

day_analysis = day_analysis.sort_values('day_of_week')

day_analysis

,day_of_week,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,Tuesday,1608,948,660,41.044776

In [83]:
print("Start date:", df['event_time'].min())
print("End date:", df['event_time'].max())

print("\nEvent dates:")
print(df['event_time'].dt.date.nunique())

Start date: 2019-10-01 00:00:00+00:00
End date: 2019-10-01 06:06:57+00:00

Event dates:
1

In [84]:
print(
    df.groupby(df['event_time'].dt.date)
      .size()
      .head(20)
)

event_time
2019-10-01    124817
dtype: int64

In [85]:
import pandas as pd
import zipfile
import random

zip_path = "data/cart_dataset.zip"

sample_size = 200000
chunk_size = 100000

samples = []

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("2019-Oct.csv") as f:

        for chunk in pd.read_csv(f, chunksize=chunk_size):

            # Take a random sample from each chunk
            n = min(
                len(chunk),
                sample_size // 50
            )

            samples.append(
                chunk.sample(n=n, random_state=42)
            )

            if sum(len(x) for x in samples) >= sample_size:
                break

df_month = pd.concat(samples, ignore_index=True)

print("Shape:", df_month.shape)
print("Start:", df_month['event_time'].min())
print("End:", df_month['event_time'].max())

Shape: (200000, 9)
Start: 2019-10-01 00:00:58 UTC
End: 2019-10-05 01:32:43 UTC

In [86]:
import pandas as pd
import zipfile

zip_path = "data/cart_dataset.zip"
sample_size = 200000
chunk_size = 100000

reservoir = pd.DataFrame()

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("2019-Oct.csv") as f:

        for chunk in pd.read_csv(f, chunksize=chunk_size):

            reservoir = pd.concat(
                [reservoir, chunk],
                ignore_index=True
            )

            if len(reservoir) > sample_size:
                reservoir = reservoir.sample(
                    n=sample_size,
                    random_state=42
                ).reset_index(drop=True)

print("Shape:", reservoir.shape)

Shape: (200000, 9)

In [87]:
df_month = reservoir.copy()

df_month['event_time'] = pd.to_datetime(
    df_month['event_time']
)

print("Start:", df_month['event_time'].min())
print("End:", df_month['event_time'].max())

print(
    "Number of dates:",
    df_month['event_time'].dt.date.nunique()
)

Start: 2019-10-29 15:01:59+00:00
End: 2019-10-31 23:59:59+00:00
Number of dates: 3

In [88]:
import pandas as pd
import zipfile

zip_path = "data/cart_dataset.zip"

chunk_size = 100000
samples = []

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("2019-Oct.csv") as f:

        for chunk in pd.read_csv(f, chunksize=chunk_size):

            # Take 500 random rows from every chunk
            sample = chunk.sample(
                n=min(500, len(chunk)),
                random_state=42
            )

            samples.append(sample)

df_month = pd.concat(
    samples,
    ignore_index=True
)

print("Shape:", df_month.shape)

df_month['event_time'] = pd.to_datetime(
    df_month['event_time']
)

print("Start:", df_month['event_time'].min())
print("End:", df_month['event_time'].max())

print(
    "Number of dates:",
    df_month['event_time'].dt.date.nunique()
)

Shape: (212500, 9)
Start: 2019-10-01 00:01:14+00:00
End: 2019-10-31 23:59:33+00:00
Number of dates: 31

In [89]:
df = df_month.copy()

print(df.shape)
print(df.info())

(212500, 9)
<class 'pandas.DataFrame'>
RangeIndex: 212500 entries, 0 to 212499
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     212500 non-null  datetime64[us, UTC]
 1   event_type     212500 non-null  str
 2   product_id     212500 non-null  int64
 3   category_id    212500 non-null  int64
 4   category_code  144701 non-null  str
 5   brand          181545 non-null  str
 6   price          212500 non-null  float64
 7   user_id        212500 non-null  int64
 8   user_session   212500 non-null  str
dtypes: datetime64[us, UTC](1), float64(1), int64(3), str(4)
memory usage: 14.6 MB
None

In [90]:
df.isnull().sum()

event_time           0
event_type           0
product_id           0
category_id          0
category_code    67799
brand            30955
price                0
user_id              0
user_session         0
dtype: int64

In [91]:
df['event_type'].value_counts()

event_type
view        204206
cart          4575
purchase      3719
Name: count, dtype: int64

In [92]:
print("Before cleaning:", df.shape)

df = df.dropna(
    subset=['brand', 'category_code']
).copy()

print("After removing missing values:", df.shape)

Before cleaning: (212500, 9)
After removing missing values: (132793, 9)

In [93]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates().reset_index(drop=True)

print("Duplicates after:", df.duplicated().sum())
print("Final shape:", df.shape)

Duplicates before: 0
Duplicates after: 0
Final shape: (132793, 9)

In [94]:
session_analysis = df.groupby('user_session').agg(
    user_id=('user_id', 'first'),
    views=('event_type', lambda x: (x == 'view').sum()),
    cart_events=('event_type', lambda x: (x == 'cart').sum()),
    purchase_events=('event_type', lambda x: (x == 'purchase').sum()),
    session_start=('event_time', 'min'),
    session_end=('event_time', 'max')
).reset_index()

In [95]:
session_analysis.head()

,user_session,user_id,views,cart_events,purchase_events,session_start,session_end
0,0000c341-ceab-4141-b196-ba53d4ebf455,562786298,1,0,0,2019-10-26 17:36:05+00:00,2019-10-26 17:36:05+00:00
1,00011fb4-97d0-41b9-87ad-772ff6d12b44,564240719,1,0,0,2019-10-26 05:46:43+00:00,2019-10-26 05:46:43+00:00
2,00029da2-57bf-4f8d-bd76-2631220754f1,538043240,1,0,0,2019-10-31 20:55:27+00:00,2019-10-31 20:55:27+00:00
3,0002f25e-6eda-4cd7-bef5-0dea55c86954,519511900,0,0,1,2019-10-04 15:51:54+00:00,2019-10-04 15:51:54+00:00
4,0003c729-3377-4695-8a5a-083ff27fa495,517122869,0,0,1,2019-10-03 03:07:05+00:00,2019-10-03 03:07:05+00:00

In [96]:
cart_sessions = session_analysis[
    session_analysis['cart_events'] > 0
].copy()

In [97]:
converted_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] > 0
]

abandoned_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] == 0
]

print("Total Cart Sessions:", len(cart_sessions))
print("Converted Cart Sessions:", len(converted_cart_sessions))
print("Abandoned Cart Sessions:", len(abandoned_cart_sessions))

Total Cart Sessions: 3977
Converted Cart Sessions: 13
Abandoned Cart Sessions: 3964

In [98]:
cart_abandonment_rate = (
    len(abandoned_cart_sessions)
    / len(cart_sessions)
) * 100

cart_conversion_rate = (
    len(converted_cart_sessions)
    / len(cart_sessions)
) * 100

print("Cart Abandonment Rate:", round(cart_abandonment_rate, 2), "%")
print("Cart Conversion Rate:", round(cart_conversion_rate, 2), "%")

Cart Abandonment Rate: 99.67 %
Cart Conversion Rate: 0.33 %

In [99]:
cart_time = df[df['event_type'] == 'cart'][
    ['user_session', 'event_time']
].copy()

cart_time = cart_time.groupby('user_session').agg(
    cart_time=('event_time', 'min')
).reset_index()

In [100]:
cart_time_analysis = cart_time.merge(
    cart_sessions[
        ['user_session', 'purchase_events']
    ],
    on='user_session',
    how='left'
)

In [101]:
cart_time_analysis['hour'] = (
    cart_time_analysis['cart_time'].dt.hour
)

In [102]:
hour_analysis = cart_time_analysis.groupby('hour').agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

hour_analysis['abandoned_sessions'] = (
    hour_analysis['cart_sessions']
    - hour_analysis['converted_sessions']
)

hour_analysis['abandonment_rate'] = (
    hour_analysis['abandoned_sessions']
    / hour_analysis['cart_sessions']
) * 100

hour_analysis

,hour,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,0,27,0,27,100.000000
1,1,32,0,32,100.000000
2,2,77,0,77,100.000000
3,3,151,0,151,100.000000
4,4,189,1,188,99.470899
5,5,229,0,229,100.000000
6,6,272,1,271,99.632353
7,7,249,0,249,100.000000
8,8,284,2,282,99.295775
9,9,297,0,297,100.000000
10,10,292,1,291,99.657534
11,11,247,0,247,100.000000
12,12,235,1,234,99.574468
13,13,219,2,217,99.086758
14,14,237,1,236,99.578059
15,15,234,3,231,98.717949
16,16,197,1,196,99.492386
17,17,163,0,163,100.000000
18,18,140,0,140,100.000000
19,19,86,0,86,100.000000
20,20,52,0,52,100.000000
21,21,28,0,28,100.000000
22,22,22,0,22,100.000000
23,23,18,0,18,100.000000

In [103]:
cart_time_analysis['day_of_week'] = (
    cart_time_analysis['cart_time'].dt.day_name()
)

day_analysis = cart_time_analysis.groupby(
    'day_of_week'
).agg(
    cart_sessions=('user_session', 'nunique'),
    converted_sessions=('purchase_events', lambda x: (x > 0).sum())
).reset_index()

day_analysis['abandoned_sessions'] = (
    day_analysis['cart_sessions']
    - day_analysis['converted_sessions']
)

day_analysis['abandonment_rate'] = (
    day_analysis['abandoned_sessions']
    / day_analysis['cart_sessions']
) * 100

day_analysis

,day_of_week,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,Friday,607,1,606,99.835255
1,Monday,474,0,474,100.000000
2,Saturday,569,2,567,99.648506
3,Sunday,590,5,585,99.152542
4,Thursday,537,1,536,99.813780
5,Tuesday,625,3,622,99.520000
6,Wednesday,575,1,574,99.826087

In [104]:
day_order = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
]

day_analysis['day_of_week'] = pd.Categorical(
    day_analysis['day_of_week'],
    categories=day_order,
    ordered=True
)

day_analysis = day_analysis.sort_values('day_of_week')

day_analysis

,day_of_week,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
1,Monday,474,0,474,100.000000
5,Tuesday,625,3,622,99.520000
6,Wednesday,575,1,574,99.826087
4,Thursday,537,1,536,99.813780
0,Friday,607,1,606,99.835255
2,Saturday,569,2,567,99.648506
3,Sunday,590,5,585,99.152542

In [105]:
import pandas as pd
import zipfile

zip_path = "data/cart_dataset.zip"

session_ids = set()

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("2019-Oct.csv") as f:

        for chunk in pd.read_csv(
            f,
            usecols=['user_session'],
            chunksize=100000
        ):
            session_ids.update(
                chunk['user_session'].dropna().unique()
            )

print("Total unique sessions:", len(session_ids))

Total unique sessions: 9244421

In [106]:
import random

random.seed(42)

sample_session_ids = random.sample(
    list(session_ids),
    min(20000, len(session_ids))
)

sample_session_ids = set(sample_session_ids)

print("Selected sessions:", len(sample_session_ids))

Selected sessions: 20000

In [107]:
session_sample = []

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("2019-Oct.csv") as f:

        for chunk in pd.read_csv(f, chunksize=100000):

            selected = chunk[
                chunk['user_session'].isin(sample_session_ids)
            ]

            if len(selected) > 0:
                session_sample.append(selected)

df = pd.concat(
    session_sample,
    ignore_index=True
)

print("Final shape:", df.shape)
print("Unique sessions:", df['user_session'].nunique())
print("Start:", df['event_time'].min())
print("End:", df['event_time'].max())

Final shape: (93109, 9)
Unique sessions: 20000
Start: 2019-10-01 00:02:19 UTC
End: 2019-10-31 23:39:31 UTC

In [111]:
print(df.shape)

(93109, 9)

In [112]:
missing = df.isna().sum()
print(missing)

event_time           0
event_type           0
product_id           0
category_id          0
category_code    29159
brand            13606
price                0
user_id              0
user_session         0
dtype: int64

In [113]:
df = df.dropna(subset=['brand', 'category_code'])

In [114]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 68

In [115]:
print("Before removing duplicates:", df.shape)

df = df.drop_duplicates().reset_index(drop=True)

print("After removing duplicates:", df.shape)
print("Duplicates remaining:", df.duplicated().sum())

Before removing duplicates: (58546, 9)
After removing duplicates: (58478, 9)
Duplicates remaining: 0

In [116]:
df['event_time'] = pd.to_datetime(df['event_time'])

print(df['event_time'].dtype)

datetime64[us, UTC]

In [117]:
session_analysis = df.groupby('user_session').agg(
    user_id=('user_id', 'first'),
    views=('event_type', lambda x: (x == 'view').sum()),
    cart_events=('event_type', lambda x: (x == 'cart').sum()),
    purchase_events=('event_type', lambda x: (x == 'purchase').sum()),
    session_start=('event_time', 'min'),
    session_end=('event_time', 'max')
).reset_index()

print(session_analysis.head())
print("Total sessions:", len(session_analysis))

                           user_session    user_id  views  cart_events  \
0  00095134-5d1b-4bf6-b1e4-25298491db47  529432648      2            0
1  000f6f2e-91d8-46c7-a74c-14faa27b1fb8  534279450     21            0
2  001376ec-cf2e-4cbb-bc54-fa6c84fbf316  518739929      2            0
3  0016c631-c3af-45cf-9dd7-a81f49dbfbc2  513061444      2            0
4  001df61b-3a22-4caf-a3ad-bb0ab9d05cc9  531129635      5            0

   purchase_events             session_start               session_end
0                0 2019-10-02 14:35:52+00:00 2019-10-02 14:36:00+00:00
1                0 2019-10-01 09:24:38+00:00 2019-10-01 09:54:11+00:00
2                0 2019-10-09 18:44:05+00:00 2019-10-09 18:46:34+00:00
3                0 2019-10-12 07:00:32+00:00 2019-10-12 07:00:44+00:00
4                0 2019-10-12 08:06:17+00:00 2019-10-12 08:08:15+00:00
Total sessions: 13910

In [118]:
cart_sessions = session_analysis[
    session_analysis['cart_events'] > 0
].copy()

converted_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] > 0
]

abandoned_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] == 0
]

print("Total Cart Sessions:", len(cart_sessions))
print("Converted Cart Sessions:", len(converted_cart_sessions))
print("Abandoned Cart Sessions:", len(abandoned_cart_sessions))

Total Cart Sessions: 1094
Converted Cart Sessions: 587
Abandoned Cart Sessions: 507

In [119]:
cart_abandonment_rate = (
    len(abandoned_cart_sessions) / len(cart_sessions)
) * 100

cart_conversion_rate = (
    len(converted_cart_sessions) / len(cart_sessions)
) * 100

print("Cart Abandonment Rate:", round(cart_abandonment_rate, 2), "%")
print("Cart Conversion Rate:", round(cart_conversion_rate, 2), "%")

Cart Abandonment Rate: 46.34 %
Cart Conversion Rate: 53.66 %

In [120]:
print("Rows:", len(df))
print("Unique sessions in df:", df['user_session'].nunique())
print("Unique sessions in original sample:", len(sample_session_ids))

Rows: 58478
Unique sessions in df: 13910
Unique sessions in original sample: 20000

In [121]:
print(
    "Sessions missing from df:",
    len(sample_session_ids - set(df['user_session'].unique()))
)

Sessions missing from df: 6090

In [122]:
import pandas as pd
import zipfile

zip_path = "data/cart_dataset.zip"

session_sample = []

with zipfile.ZipFile(zip_path, "r") as z:
    with z.open("2019-Oct.csv") as f:

        for chunk in pd.read_csv(f, chunksize=100000):

            selected = chunk[
                chunk['user_session'].isin(sample_session_ids)
            ]

            if not selected.empty:
                session_sample.append(selected)

df = pd.concat(session_sample, ignore_index=True)

print("Reloaded shape:", df.shape)
print("Unique sessions:", df['user_session'].nunique())

Reloaded shape: (93109, 9)
Unique sessions: 20000

In [123]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 95

In [124]:
df = df.drop_duplicates().reset_index(drop=True)

print("After duplicates:", df.shape)
print("Unique sessions:", df['user_session'].nunique())

After duplicates: (93014, 9)
Unique sessions: 20000

In [125]:
# Convert event_time to datetime
df['event_time'] = pd.to_datetime(df['event_time'])

# Create session-level summary
session_analysis = df.groupby('user_session').agg(
    user_id=('user_id', 'first'),
    views=('event_type', lambda x: (x == 'view').sum()),
    cart_events=('event_type', lambda x: (x == 'cart').sum()),
    purchase_events=('event_type', lambda x: (x == 'purchase').sum()),
    session_start=('event_time', 'min'),
    session_end=('event_time', 'max')
).reset_index()

print("Total sessions:", len(session_analysis))
print(session_analysis.head())

Total sessions: 20000
                           user_session    user_id  views  cart_events  \
0  00002e45-650a-4dbb-bbe6-29d709fb652f  513595796      8            0
1  00095134-5d1b-4bf6-b1e4-25298491db47  529432648      2            0
2  00095607-9518-42ce-9789-107189a853fd  531516671     30            0
3  000a7785-22e9-4110-b6da-78321ddba4ea  528052417      4            0
4  000f6f2e-91d8-46c7-a74c-14faa27b1fb8  534279450     21            0

   purchase_events             session_start               session_end
0                0 2019-10-13 08:41:09+00:00 2019-10-13 08:52:19+00:00
1                0 2019-10-02 14:35:52+00:00 2019-10-02 14:36:00+00:00
2                1 2019-10-05 16:49:57+00:00 2019-10-05 17:06:04+00:00
3                0 2019-10-27 22:25:47+00:00 2019-10-27 22:33:56+00:00
4                0 2019-10-01 09:24:38+00:00 2019-10-01 09:54:11+00:00

In [126]:
cart_sessions = session_analysis[
    session_analysis['cart_events'] > 0
].copy()

converted_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] > 0
]

abandoned_cart_sessions = cart_sessions[
    cart_sessions['purchase_events'] == 0
]

print("Total Cart Sessions:", len(cart_sessions))
print("Converted Cart Sessions:", len(converted_cart_sessions))
print("Abandoned Cart Sessions:", len(abandoned_cart_sessions))

Total Cart Sessions: 1240
Converted Cart Sessions: 649
Abandoned Cart Sessions: 591

In [127]:
cart_abandonment_rate = (
    len(abandoned_cart_sessions) / len(cart_sessions)
) * 100

cart_conversion_rate = (
    len(converted_cart_sessions) / len(cart_sessions)
) * 100

print("Cart Abandonment Rate:", round(cart_abandonment_rate, 2), "%")
print("Cart Conversion Rate:", round(cart_conversion_rate, 2), "%")

Cart Abandonment Rate: 47.66 %
Cart Conversion Rate: 52.34 %

In [128]:
print("===== OVERALL KPIs =====")

print("Total Sessions:", len(session_analysis))

print("Total Users:", df['user_id'].nunique())

print("Total Events:", len(df))

print("Total Views:", (df['event_type'] == 'view').sum())

print("Total Cart Events:", (df['event_type'] == 'cart').sum())

print("Total Purchase Events:", (df['event_type'] == 'purchase').sum())

print("Cart Sessions:", len(cart_sessions))

print("Converted Cart Sessions:", len(converted_cart_sessions))

print("Abandoned Cart Sessions:", len(abandoned_cart_sessions))

print("Cart Abandonment Rate:", round(cart_abandonment_rate, 2), "%")

===== OVERALL KPIs =====
Total Sessions: 20000
Total Users: 19796
Total Events: 93014
Total Views: 89436
Total Cart Events: 1972
Total Purchase Events: 1606
Cart Sessions: 1240
Converted Cart Sessions: 649
Abandoned Cart Sessions: 591
Cart Abandonment Rate: 47.66 %

In [129]:
funnel = {
    'Viewed': (session_analysis['views'] > 0).sum(),
    'Added to Cart': (session_analysis['cart_events'] > 0).sum(),
    'Purchased': (session_analysis['purchase_events'] > 0).sum()
}

print(funnel)

{'Viewed': np.int64(19996), 'Added to Cart': np.int64(1240), 'Purchased': np.int64(1393)}

In [130]:
view_to_cart_rate = (
    funnel['Added to Cart'] / funnel['Viewed']
) * 100

cart_to_purchase_rate = (
    funnel['Purchased'] / funnel['Added to Cart']
) * 100

print("View → Cart Rate:", round(view_to_cart_rate, 2), "%")
print("Cart → Purchase Rate:", round(cart_to_purchase_rate, 2), "%")

View → Cart Rate: 6.2 %
Cart → Purchase Rate: 112.34 %

In [131]:
session_analysis['session_duration_minutes'] = (
    session_analysis['session_end'] -
    session_analysis['session_start']
).dt.total_seconds() / 60

print(session_analysis[['user_session', 'session_duration_minutes']].head())

                           user_session  session_duration_minutes
0  00002e45-650a-4dbb-bbe6-29d709fb652f                 11.166667
1  00095134-5d1b-4bf6-b1e4-25298491db47                  0.133333
2  00095607-9518-42ce-9789-107189a853fd                 16.116667
3  000a7785-22e9-4110-b6da-78321ddba4ea                  8.150000
4  000f6f2e-91d8-46c7-a74c-14faa27b1fb8                 29.550000

In [132]:
converted_duration = converted_cart_sessions.merge(
    session_analysis[['user_session', 'session_duration_minutes']],
    on='user_session'
)

abandoned_duration = abandoned_cart_sessions.merge(
    session_analysis[['user_session', 'session_duration_minutes']],
    on='user_session'
)

print("Average converted session duration:",
      round(converted_duration['session_duration_minutes'].mean(), 2),
      "minutes")

print("Average abandoned session duration:",
      round(abandoned_duration['session_duration_minutes'].mean(), 2),
      "minutes")

Average converted session duration: 9.57 minutes
Average abandoned session duration: 10.87 minutes

In [133]:
converted_views = converted_cart_sessions['views'].mean()
abandoned_views = abandoned_cart_sessions['views'].mean()

print("Average views - Converted:",
      round(converted_views, 2))

print("Average views - Abandoned:",
      round(abandoned_views, 2))

Average views - Converted: 5.26
Average views - Abandoned: 6.72

In [134]:
print(
    "Average cart events - Converted:",
    round(converted_cart_sessions['cart_events'].mean(), 2)
)

print(
    "Average cart events - Abandoned:",
    round(abandoned_cart_sessions['cart_events'].mean(), 2)
)

Average cart events - Converted: 1.63
Average cart events - Abandoned: 1.54

In [135]:
cart_time = (
    df[df['event_type'] == 'cart']
    .groupby('user_session')['event_time']
    .min()
    .reset_index()
)

cart_time = cart_time.rename(
    columns={'event_time': 'first_cart_time'}
)

cart_time = cart_time.merge(
    cart_sessions[['user_session', 'purchase_events']],
    on='user_session',
    how='left'
)

cart_time['hour'] = cart_time['first_cart_time'].dt.hour

cart_time['status'] = cart_time['purchase_events'].apply(
    lambda x: 'Converted' if x > 0 else 'Abandoned'
)

print(cart_time.head())

                           user_session           first_cart_time  \
0  0087241b-c4e7-4215-8471-8c1fddba341c 2019-10-15 13:35:28+00:00
1  00a40a76-b459-46d2-be3a-a0b32d9f14a1 2019-10-06 13:49:20+00:00
2  00aede32-3f6f-4dad-ad0e-92f7b9e11a45 2019-10-17 06:40:34+00:00
3  00f7e5e8-2a59-4214-8866-9e1f73cab31c 2019-10-25 04:51:13+00:00
4  01391222-1121-41ab-b178-a653ba1a8102 2019-10-14 22:25:46+00:00

   purchase_events  hour     status
0                0    13  Abandoned
1                1    13  Converted
2                1     6  Converted
3                0     4  Abandoned
4                0    22  Abandoned

In [136]:
hourly_analysis = (
    cart_time
    .groupby('hour')
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=('purchase_events', lambda x: (x > 0).sum())
    )
    .reset_index()
)

hourly_analysis['abandoned_sessions'] = (
    hourly_analysis['cart_sessions'] -
    hourly_analysis['converted_sessions']
)

hourly_analysis['abandonment_rate'] = (
    hourly_analysis['abandoned_sessions'] /
    hourly_analysis['cart_sessions'] * 100
)

print(hourly_analysis)

    hour  cart_sessions  converted_sessions  abandoned_sessions  \
0      0              6                   5                   1
1      1             10                   2                   8
2      2             23                  10                  13
3      3             51                  26                  25
4      4             56                  33                  23
5      5             61                  30                  31
6      6             67                  36                  31
7      7             94                  51                  43
8      8             92                  48                  44
9      9             97                  52                  45
10    10             96                  59                  37
11    11             77                  41                  36
12    12             82                  43                  39
13    13             85                  45                  40
14    14             61                  31                  30
15    15             56                  31                  25
16    16             72                  41                  31
17    17             55                  27                  28
18    18             39                  15                  24
19    19             19                   7                  12
20    20             17                   5                  12
21    21             13                   6                   7
22    22              8                   4                   4
23    23              3                   1                   2

    abandonment_rate
0          16.666667
1          80.000000
2          56.521739
3          49.019608
4          41.071429
5          50.819672
6          46.268657
7          45.744681
8          47.826087
9          46.391753
10         38.541667
11         46.753247
12         47.560976
13         47.058824
14         49.180328
15         44.642857
16         43.055556
17         50.909091
18         61.538462
19         63.157895
20         70.588235
21         53.846154
22         50.000000
23         66.666667

In [137]:
hourly_reliable = hourly_analysis[
    hourly_analysis['cart_sessions'] >= 30
].copy()

print(hourly_reliable)

    hour  cart_sessions  converted_sessions  abandoned_sessions  \
3      3             51                  26                  25
4      4             56                  33                  23
5      5             61                  30                  31
6      6             67                  36                  31
7      7             94                  51                  43
8      8             92                  48                  44
9      9             97                  52                  45
10    10             96                  59                  37
11    11             77                  41                  36
12    12             82                  43                  39
13    13             85                  45                  40
14    14             61                  31                  30
15    15             56                  31                  25
16    16             72                  41                  31
17    17             55                  27                  28
18    18             39                  15                  24

    abandonment_rate
3          49.019608
4          41.071429
5          50.819672
6          46.268657
7          45.744681
8          47.826087
9          46.391753
10         38.541667
11         46.753247
12         47.560976
13         47.058824
14         49.180328
15         44.642857
16         43.055556
17         50.909091
18         61.538462

In [138]:
print("Highest abandonment among hours with >=30 cart sessions:")
print(
    hourly_reliable.loc[
        hourly_reliable['abandonment_rate'].idxmax()
    ]
)

print("\nLowest abandonment among hours with >=30 cart sessions:")
print(
    hourly_reliable.loc[
        hourly_reliable['abandonment_rate'].idxmin()
    ]
)

Highest abandonment among hours with >=30 cart sessions:
hour                  18.000000
cart_sessions         39.000000
converted_sessions    15.000000
abandoned_sessions    24.000000
abandonment_rate      61.538462
Name: 18, dtype: float64

Lowest abandonment among hours with >=30 cart sessions:
hour                  10.000000
cart_sessions         96.000000
converted_sessions    59.000000
abandoned_sessions    37.000000
abandonment_rate      38.541667
Name: 10, dtype: float64

In [139]:
cart_time['day_of_week'] = cart_time['first_cart_time'].dt.day_name()

daily_analysis = (
    cart_time
    .groupby('day_of_week')
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=('purchase_events', lambda x: (x > 0).sum())
    )
    .reset_index()
)

daily_analysis['abandoned_sessions'] = (
    daily_analysis['cart_sessions'] -
    daily_analysis['converted_sessions']
)

daily_analysis['abandonment_rate'] = (
    daily_analysis['abandoned_sessions'] /
    daily_analysis['cart_sessions'] * 100
)

# Put days in normal Monday → Sunday order
day_order = [
    'Monday', 'Tuesday', 'Wednesday',
    'Thursday', 'Friday', 'Saturday', 'Sunday'
]

daily_analysis['day_of_week'] = pd.Categorical(
    daily_analysis['day_of_week'],
    categories=day_order,
    ordered=True
)

daily_analysis = daily_analysis.sort_values('day_of_week')

print(daily_analysis)

  day_of_week  cart_sessions  converted_sessions  abandoned_sessions  \
1      Monday            176                  86                  90
5     Tuesday            202                 110                  92
6   Wednesday            173                 101                  72
4    Thursday            168                  95                  73
0      Friday            182                  85                  97
2    Saturday            167                  85                  82
3      Sunday            172                  87                  85

   abandonment_rate
1         51.136364
5         45.544554
6         41.618497
4         43.452381
0         53.296703
2         49.101796
3         49.418605

In [140]:
category_data = df[
    df['event_type'] == 'cart'
].copy()

category_data['category_code'] = (
    category_data['category_code']
    .fillna('Unknown')
)

print("Cart events:", len(category_data))
print("Unique categories:", category_data['category_code'].nunique())

Cart events: 1972
Unique categories: 51

In [141]:
category_analysis = (
    category_data
    .groupby('category_code')
    .agg(
        cart_events=('user_session', 'count'),
        cart_sessions=('user_session', 'nunique')
    )
    .reset_index()
)

print(category_analysis.sort_values(
    'cart_sessions',
    ascending=False
).head(20))

                       category_code  cart_events  cart_sessions
43            electronics.smartphone         1228            759
0                            Unknown          197            141
39       electronics.audio.headphone           73             56
46              electronics.video.tv           73             44
19         appliances.kitchen.washer           54             35
42                electronics.clocks           53             35
30                computers.notebook           44             29
4      appliances.environment.vacuum           38             24
18  appliances.kitchen.refrigerators           23             20
13         appliances.kitchen.kettle           15              9
44                electronics.tablet           10              9
45             electronics.telephone           11              8
8         appliances.kitchen.blender           10              6
28                 computers.desktop            6              6
6                    appliances.iron            7              5
14   appliances.kitchen.meat_grinder            5              5
22        appliances.personal.scales            4              4
36            construction.tools.saw            9              4
25            auto.accessories.radar            9              4
23         appliances.sewing_machine            9              4

In [142]:
category_session = category_data[
    ['user_session', 'category_code']
].drop_duplicates()

category_session = category_session.merge(
    cart_sessions[['user_session', 'purchase_events']],
    on='user_session',
    how='left'
)

category_abandonment = (
    category_session
    .groupby('category_code')
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=(
            'purchase_events',
            lambda x: (x > 0).sum()
        )
    )
    .reset_index()
)

category_abandonment['abandoned_sessions'] = (
    category_abandonment['cart_sessions'] -
    category_abandonment['converted_sessions']
)

category_abandonment['abandonment_rate'] = (
    category_abandonment['abandoned_sessions'] /
    category_abandonment['cart_sessions'] * 100
)

print(
    category_abandonment
    .sort_values('cart_sessions', ascending=False)
    .head(20)
)

                       category_code  cart_sessions  converted_sessions  \
43            electronics.smartphone            759                 442
0                            Unknown            141                  61
39       electronics.audio.headphone             56                  21
46              electronics.video.tv             44                  26
19         appliances.kitchen.washer             35                  14
42                electronics.clocks             35                  16
30                computers.notebook             29                  15
4      appliances.environment.vacuum             24                  11
18  appliances.kitchen.refrigerators             20                   8
13         appliances.kitchen.kettle              9                   4
44                electronics.tablet              9                   5
45             electronics.telephone              8                   5
8         appliances.kitchen.blender              6                   3
28                 computers.desktop              6                   5
6                    appliances.iron              5                   2
14   appliances.kitchen.meat_grinder              5                   2
22        appliances.personal.scales              4                   1
36            construction.tools.saw              4                   1
25            auto.accessories.radar              4                   0
23         appliances.sewing_machine              4                   2

    abandoned_sessions  abandonment_rate
43                 317         41.765481
0                   80         56.737589
39                  35         62.500000
46                  18         40.909091
19                  21         60.000000
42                  19         54.285714
30                  14         48.275862
4                   13         54.166667
18                  12         60.000000
13                   5         55.555556
44                   4         44.444444
45                   3         37.500000
8                    3         50.000000
28                   1         16.666667
6                    3         60.000000
14                   3         60.000000
22                   3         75.000000
36                   3         75.000000
25                   4        100.000000
23                   2         50.000000

In [143]:
category_reliable = category_abandonment[
    category_abandonment['cart_sessions'] >= 20
].copy()

print(
    category_reliable
    .sort_values('abandonment_rate', ascending=False)
)

                       category_code  cart_sessions  converted_sessions  \
39       electronics.audio.headphone             56                  21
19         appliances.kitchen.washer             35                  14
18  appliances.kitchen.refrigerators             20                   8
0                            Unknown            141                  61
42                electronics.clocks             35                  16
4      appliances.environment.vacuum             24                  11
30                computers.notebook             29                  15
43            electronics.smartphone            759                 442
46              electronics.video.tv             44                  26

    abandoned_sessions  abandonment_rate
39                  35         62.500000
19                  21         60.000000
18                  12         60.000000
0                   80         56.737589
42                  19         54.285714
4                   13         54.166667
30                  14         48.275862
43                 317         41.765481
46                  18         40.909091

In [144]:
brand_data = df[
    df['event_type'] == 'cart'
].copy()

brand_data['brand'] = (
    brand_data['brand']
    .fillna('Unknown')
)

print("Cart events:", len(brand_data))
print("Unique brands:", brand_data['brand'].nunique())

Cart events: 1972
Unique brands: 105

In [145]:
brand_session = brand_data[
    ['user_session', 'brand']
].drop_duplicates()

brand_session = brand_session.merge(
    cart_sessions[['user_session', 'purchase_events']],
    on='user_session',
    how='left'
)

brand_analysis = (
    brand_session
    .groupby('brand')
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=(
            'purchase_events',
            lambda x: (x > 0).sum()
        )
    )
    .reset_index()
)

brand_analysis['abandoned_sessions'] = (
    brand_analysis['cart_sessions'] -
    brand_analysis['converted_sessions']
)

brand_analysis['abandonment_rate'] = (
    brand_analysis['abandoned_sessions'] /
    brand_analysis['cart_sessions'] * 100
)

In [146]:
brand_reliable = brand_analysis[
    brand_analysis['cart_sessions'] >= 20
].copy()

print(
    brand_reliable
    .sort_values('abandonment_rate', ascending=False)
)

       brand  cart_sessions  converted_sessions  abandoned_sessions  \
0    Unknown             23                   8                  15
102   xiaomi            153                  64                  89
4      apple            301                 163                 138
45    huawei             44                  26                  18
72      oppo             37                  22                  15
87   samsung            403                 249                 154

     abandonment_rate
0           65.217391
102         58.169935
4           45.847176
45          40.909091
72          40.540541
87          38.213400

In [147]:
product_data = df[
    df['event_type'] == 'cart'
].copy()

product_data['category_code'] = (
    product_data['category_code']
    .fillna('Unknown')
)

product_data['brand'] = (
    product_data['brand']
    .fillna('Unknown')
)

print("Cart events:", len(product_data))
print("Unique products:", product_data['product_id'].nunique())

Cart events: 1972
Unique products: 531

In [148]:
product_session = product_data[
    [
        'user_session',
        'product_id',
        'category_code',
        'brand',
        'price'
    ]
].drop_duplicates()

product_session = product_session.merge(
    cart_sessions[['user_session', 'purchase_events']],
    on='user_session',
    how='left'
)

product_analysis = (
    product_session
    .groupby(
        ['product_id', 'category_code', 'brand'],
        as_index=False
    )
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=(
            'purchase_events',
            lambda x: (x > 0).sum()
        ),
        average_price=('price', 'mean')
    )
)

product_analysis['abandoned_sessions'] = (
    product_analysis['cart_sessions'] -
    product_analysis['converted_sessions']
)

product_analysis['abandonment_rate'] = (
    product_analysis['abandoned_sessions'] /
    product_analysis['cart_sessions'] * 100
)

In [149]:
product_reliable = product_analysis[
    product_analysis['cart_sessions'] >= 5
].copy()

print(
    product_reliable
    .sort_values('abandonment_rate', ascending=False)
    .head(20)
)

     product_id                category_code    brand  cart_sessions  \
346     4804295  electronics.audio.headphone   xiaomi             10
144     1005135       electronics.smartphone    apple              6
71      1004794       electronics.smartphone   xiaomi              5
29      1004237       electronics.smartphone    apple              6
128     1005105       electronics.smartphone    apple             15
68      1004781       electronics.smartphone   huawei              6
36      1004250       electronics.smartphone    apple              6
150     1005160       electronics.smartphone   xiaomi              6
369     5100816                      Unknown   xiaomi             25
344     4804056  electronics.audio.headphone    apple             25
203     1801690         electronics.video.tv  samsung              8
39      1004258       electronics.smartphone    apple              5
52      1004720       electronics.smartphone   huawei              5
359     5100566           electronics.clocks    apple              5
371     5100855           electronics.clocks    apple              5
53      1004739       electronics.smartphone   xiaomi             17
35      1004249       electronics.smartphone    apple             31
69      1004785       electronics.smartphone   huawei              9
55      1004741       electronics.smartphone   xiaomi             24
79      1004838       electronics.smartphone     oppo             10

     converted_sessions  average_price  abandoned_sessions  abandonment_rate
346                   0      23.019000                  10        100.000000
144                   1    1728.448333                   5         83.333333
71                    1     226.042000                   4         80.000000
29                    2    1089.576667                   4         66.666667
128                   5    1396.908000                  10         66.666667
68                    2     268.285000                   4         66.666667
36                    2     794.583333                   4         66.666667
150                   2     217.650000                   4         66.666667
369                   9      28.615200                  16         64.000000
344                   9     160.491200                  16         64.000000
203                   3     370.432500                   5         62.500000
39                    2     733.406000                   3         60.000000
52                    2     126.896000                   3         60.000000
359                   2     453.926000                   3         60.000000
371                   2     592.446000                   3         60.000000
53                    7     192.441765                  10         58.823529
35                   13     742.542581                  18         58.064516
69                    4     270.603333                   5         55.555556
55                   11     190.770000                  13         54.166667
79                    5     170.910000                   5         50.000000

In [150]:
price_data = product_data.copy()

price_data['price_range'] = pd.cut(
    price_data['price'],
    bins=[0, 50, 100, 250, 500, 1000, float('inf')],
    labels=[
        '0-50',
        '51-100',
        '101-250',
        '251-500',
        '501-1000',
        '1000+'
    ]
)

print(price_data['price_range'].value_counts().sort_index())

price_range
0-50        187
51-100      181
101-250     797
251-500     431
501-1000    252
1000+       124
Name: count, dtype: int64

In [151]:
price_session = price_data[
    ['user_session', 'price_range']
].drop_duplicates()

price_session = price_session.merge(
    cart_sessions[['user_session', 'purchase_events']],
    on='user_session',
    how='left'
)

price_analysis = (
    price_session
    .groupby('price_range', observed=True)
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=(
            'purchase_events',
            lambda x: (x > 0).sum()
        )
    )
    .reset_index()
)

price_analysis['abandoned_sessions'] = (
    price_analysis['cart_sessions'] -
    price_analysis['converted_sessions']
)

price_analysis['abandonment_rate'] = (
    price_analysis['abandoned_sessions'] /
    price_analysis['cart_sessions'] * 100
)

print(price_analysis)

  price_range  cart_sessions  converted_sessions  abandoned_sessions  \
0        0-50            132                  52                  80
1      51-100            107                  50                  57
2     101-250            496                 279                 217
3     251-500            277                 164                 113
4    501-1000            168                  88                  80
5       1000+             96                  43                  53

   abandonment_rate
0         60.606061
1         53.271028
2         43.750000
3         40.794224
4         47.619048
5         55.208333

In [152]:
price_analysis.sort_values(
    'cart_sessions',
    ascending=False
)

,price_range,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
2,101-250,496,279,217,43.750000
3,251-500,277,164,113,40.794224
4,501-1000,168,88,80,47.619048
0,0-50,132,52,80,60.606061
1,51-100,107,50,57,53.271028
5,1000+,96,43,53,55.208333

In [153]:
price_analysis.sort_values(
    'cart_sessions',
    ascending=False
).reset_index(drop=True)

,price_range,cart_sessions,converted_sessions,abandoned_sessions,abandonment_rate
0,101-250,496,279,217,43.750000
1,251-500,277,164,113,40.794224
2,501-1000,168,88,80,47.619048
3,0-50,132,52,80,60.606061
4,51-100,107,50,57,53.271028
5,1000+,96,43,53,55.208333

In [154]:
cart_time = (
    df[df['event_type'] == 'cart']
    .groupby('user_session')['event_time']
    .min()
    .reset_index()
)

cart_time = cart_time.rename(
    columns={'event_time': 'first_cart_time'}
)

cart_time = cart_time.merge(
    cart_sessions[['user_session', 'purchase_events']],
    on='user_session',
    how='left'
)

cart_time['hour'] = cart_time['first_cart_time'].dt.hour

cart_time['status'] = cart_time['purchase_events'].apply(
    lambda x: 'Converted' if x > 0 else 'Abandoned'
)

In [155]:
hourly_analysis = (
    cart_time
    .groupby('hour')
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=('purchase_events', lambda x: (x > 0).sum())
    )
    .reset_index()
)

hourly_analysis['abandoned_sessions'] = (
    hourly_analysis['cart_sessions']
    - hourly_analysis['converted_sessions']
)

hourly_analysis['abandonment_rate'] = (
    hourly_analysis['abandoned_sessions']
    / hourly_analysis['cart_sessions']
    * 100
)

print(hourly_analysis)

    hour  cart_sessions  converted_sessions  abandoned_sessions  \
0      0              6                   5                   1
1      1             10                   2                   8
2      2             23                  10                  13
3      3             51                  26                  25
4      4             56                  33                  23
5      5             61                  30                  31
6      6             67                  36                  31
7      7             94                  51                  43
8      8             92                  48                  44
9      9             97                  52                  45
10    10             96                  59                  37
11    11             77                  41                  36
12    12             82                  43                  39
13    13             85                  45                  40
14    14             61                  31                  30
15    15             56                  31                  25
16    16             72                  41                  31
17    17             55                  27                  28
18    18             39                  15                  24
19    19             19                   7                  12
20    20             17                   5                  12
21    21             13                   6                   7
22    22              8                   4                   4
23    23              3                   1                   2

    abandonment_rate
0          16.666667
1          80.000000
2          56.521739
3          49.019608
4          41.071429
5          50.819672
6          46.268657
7          45.744681
8          47.826087
9          46.391753
10         38.541667
11         46.753247
12         47.560976
13         47.058824
14         49.180328
15         44.642857
16         43.055556
17         50.909091
18         61.538462
19         63.157895
20         70.588235
21         53.846154
22         50.000000
23         66.666667

In [156]:
cart_time['day_of_week'] = cart_time['first_cart_time'].dt.day_name()

day_order = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
]

daily_analysis = (
    cart_time
    .groupby('day_of_week')
    .agg(
        cart_sessions=('user_session', 'nunique'),
        converted_sessions=('purchase_events', lambda x: (x > 0).sum())
    )
    .reset_index()
)

daily_analysis['abandoned_sessions'] = (
    daily_analysis['cart_sessions']
    - daily_analysis['converted_sessions']
)

daily_analysis['abandonment_rate'] = (
    daily_analysis['abandoned_sessions']
    / daily_analysis['cart_sessions']
    * 100
)

daily_analysis['day_of_week'] = pd.Categorical(
    daily_analysis['day_of_week'],
    categories=day_order,
    ordered=True
)

daily_analysis = daily_analysis.sort_values('day_of_week')

print(daily_analysis)

  day_of_week  cart_sessions  converted_sessions  abandoned_sessions  \
1      Monday            176                  86                  90
5     Tuesday            202                 110                  92
6   Wednesday            173                 101                  72
4    Thursday            168                  95                  73
0      Friday            182                  85                  97
2    Saturday            167                  85                  82
3      Sunday            172                  87                  85

   abandonment_rate
1         51.136364
5         45.544554
6         41.618497
4         43.452381
0         53.296703
2         49.101796
3         49.418605

In [157]:
session_behavior = cart_sessions.copy()

session_behavior['session_duration_minutes'] = (
    session_behavior['session_end']
    - session_behavior['session_start']
).dt.total_seconds() / 60

session_behavior['status'] = session_behavior['purchase_events'].apply(
    lambda x: 'Converted' if x > 0 else 'Abandoned'
)

behavior_summary = (
    session_behavior
    .groupby('status')
    .agg(
        sessions=('user_session', 'nunique'),
        avg_duration_minutes=('session_duration_minutes', 'mean'),
        avg_views=('views', 'mean'),
        avg_cart_events=('cart_events', 'mean')
    )
    .reset_index()
)

print(behavior_summary)

      status  sessions  avg_duration_minutes  avg_views  avg_cart_events
0  Abandoned       591             10.870333   6.719120         1.544839
1  Converted       649              9.565511   5.261941         1.631741

In [158]:
duration_diff = 10.870333 - 9.565511
views_diff = 6.719120 - 5.261941
cart_diff = 1.631741 - 1.544839

print("Duration difference:", duration_diff)
print("Views difference:", views_diff)
print("Cart event difference:", cart_diff)

Duration difference: 1.3048219999999997
Views difference: 1.457179
Cart event difference: 0.08690200000000003

In [159]:
sql_sessions = session_analysis.copy()

sql_sessions['status'] = sql_sessions['purchase_events'].apply(
    lambda x: 'Converted' if x > 0 else 'Abandoned'
)

sql_sessions['session_duration_minutes'] = (
    sql_sessions['session_end']
    - sql_sessions['session_start']
).dt.total_seconds() / 60

sql_sessions.head()

,user_session,user_id,views,cart_events,purchase_events,session_start,session_end,session_duration_minutes,status
0,00002e45-650a-4dbb-bbe6-29d709fb652f,513595796,8,0,0,2019-10-13 08:41:09+00:00,2019-10-13 08:52:19+00:00,11.166667,Abandoned
1,00095134-5d1b-4bf6-b1e4-25298491db47,529432648,2,0,0,2019-10-02 14:35:52+00:00,2019-10-02 14:36:00+00:00,0.133333,Abandoned
2,00095607-9518-42ce-9789-107189a853fd,531516671,30,0,1,2019-10-05 16:49:57+00:00,2019-10-05 17:06:04+00:00,16.116667,Converted
3,000a7785-22e9-4110-b6da-78321ddba4ea,528052417,4,0,0,2019-10-27 22:25:47+00:00,2019-10-27 22:33:56+00:00,8.150000,Abandoned
4,000f6f2e-91d8-46c7-a74c-14faa27b1fb8,534279450,21,0,0,2019-10-01 09:24:38+00:00,2019-10-01 09:54:11+00:00,29.550000,Abandoned

In [160]:
print(sql_sessions.shape)
print(sql_sessions.columns)
print(sql_sessions['status'].value_counts())

(20000, 9)
Index(['user_session', 'user_id', 'views', 'cart_events', 'purchase_events',
       'session_start', 'session_end', 'session_duration_minutes', 'status'],
      dtype='str')
status
Abandoned    18607
Converted     1393
Name: count, dtype: int64

In [161]:
sql_sessions.to_csv(
    'cart_sessions.csv',
    index=False
)

In [162]:
df.to_csv(
    'cart_events.csv',
    index=False
)

In [ ]:
print(sql_sessions.columns.tolist())